package com.example.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.example.demo.IUserService.IUserService;
import com.example.demo.entity.User;
import com.example.demo.entity.UserRequest;
import com.example.demo.entity.UserResponse;
import com.example.demo.util.JwtUtil;

@RestController
public class UserController {
	  @Autowired
	 private IUserService iUserService;
	   @Autowired
	  private JwtUtil jwtUtil;
	  // add endpoints to add the user(Register )
	  @PostMapping("/addUser")
	  public User addUser(@RequestBody User user) {
		  
		  return iUserService.saveUser(user);
	  }
	  
	  
	  // login or validate user 
	  @PostMapping("/login")
	  public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest){
		  
		     // todo:validate un/pwd with database then generate token
		  
		  String token=jwtUtil.generatetoken(userRequest.getUsername());
		  
		  return new ResponseEntity<UserResponse>(new UserResponse(token,"Success! Generated By Shrisht"),HttpStatus.OK);
	  }

}
